-- Reset the exercise catalog and add EN/PL localization.
--
-- The app currently only shows English text, but the exercise/category data
-- source now provides Polish translations too, so both are stored for future
-- bilingual support.

-- 1. Clear out plan_exercises rows first: workout_plan_exercises.exercise_id
-- is ON DELETE RESTRICT, and every existing exercise is being replaced below.
delete from public.workout_plan_exercises;
delete from public.exercises;

-- 2. Add localized name columns. `name` (English) is renamed to `name_en`
-- for clarity now that a `name_pl` counterpart exists.
alter table public.exercises rename column name to name_en;
alter table public.exercises add column name_pl text;

-- 3. Localized labels for the muscle_group enum (categories), kept in a
-- small lookup table rather than duplicated on every exercise row.
create table public.muscle_group_translations (
  muscle_group public.muscle_group primary key,
  label_en text not null,
  label_pl text not null
);

insert into public.muscle_group_translations (muscle_group, label_en, label_pl) values
  ('chest', 'Chest', 'Klatka piersiowa'),
  ('back', 'Back', 'Plecy'),
  ('shoulders', 'Shoulders', 'Barki'),
  ('legs', 'Legs', 'Nogi'),
  ('core', 'Core', 'Core'),
  ('full_body', 'Full body', 'Całe ciało'),
  ('cardio', 'Cardio', 'Cardio'),
  ('biceps', 'Biceps', 'Biceps'),
  ('triceps', 'Triceps', 'Triceps');

-- 4. Import the full bilingual exercise catalog (global rows, created_by
-- null so they're visible to every user per the existing RLS policy).
insert into public.exercises (name_en, name_pl, muscle_group) values
  ('Archer Push-Up', 'Pompki łucznicze', 'chest'::public.muscle_group),
  ('Barbell Bench Press', 'Wyciskanie sztangi leżąc', 'chest'::public.muscle_group),
  ('Cable Chest Fly', 'Rozpiętki na wyciągu w pozycji stojącej', 'chest'::public.muscle_group),
  ('Cable Crossover', 'Rozpiętki na wyciągu', 'chest'::public.muscle_group),
  ('Chest Dips', 'Pompki na poręczach na klatkę', 'chest'::public.muscle_group),
  ('Decline Barbell Bench Press', 'Wyciskanie sztangi na ławce skośnej ujemnej', 'chest'::public.muscle_group),
  ('Decline Dumbbell Press', 'Wyciskanie hantli na ławce skośnej ujemnej', 'chest'::public.muscle_group),
  ('Decline Push-Up', 'Pompki z nogami na podwyższeniu', 'chest'::public.muscle_group),
  ('Diamond Push-Up', 'Pompki diamentowe', 'chest'::public.muscle_group),
  ('Dumbbell Bench Press', 'Wyciskanie hantli leżąc', 'chest'::public.muscle_group),
  ('Dumbbell Fly', 'Rozpiętki z hantlami', 'chest'::public.muscle_group),
  ('Dumbbell Squeeze Press', 'Wyciskanie hantli z ich dociskaniem', 'chest'::public.muscle_group),
  ('Floor Press', 'Wyciskanie z hantlami na podłodze', 'chest'::public.muscle_group),
  ('High Cable Crossover', 'Rozpiętki na wyciągu z góry', 'chest'::public.muscle_group),
  ('Incline Barbell Bench Press', 'Wyciskanie sztangi na ławce skośnej dodatniej', 'chest'::public.muscle_group),
  ('Incline Dumbbell Fly', 'Rozpiętki z hantlami na ławce skośnej', 'chest'::public.muscle_group),
  ('Incline Dumbbell Press', 'Wyciskanie hantli na ławce skośnej dodatniej', 'chest'::public.muscle_group),
  ('Incline Push-Up', 'Pompki z rękami na podwyższeniu', 'chest'::public.muscle_group),
  ('Kneeling Cable Chest Press', 'Wyciskanie na wyciągu w klęku', 'chest'::public.muscle_group),
  ('Landmine Chest Press', 'Wyciskanie landmine na klatkę', 'chest'::public.muscle_group),
  ('Low Cable Crossover', 'Rozpiętki na wyciągu z dołu', 'chest'::public.muscle_group),
  ('Machine Chest Press', 'Wyciskanie na maszynie na klatkę', 'chest'::public.muscle_group),
  ('Medicine Ball Chest Pass', 'Wyrzut piłki lekarskiej sprzed klatki', 'chest'::public.muscle_group),
  ('Pec Deck', 'Rozpiętki na maszynie', 'chest'::public.muscle_group),
  ('Plate-Loaded Chest Press', 'Wyciskanie na maszynie z obciążeniem talerzowym', 'chest'::public.muscle_group),
  ('Push-Up', 'Pompki', 'chest'::public.muscle_group),
  ('Resistance Band Chest Fly', 'Rozpiętki z gumą oporową', 'chest'::public.muscle_group),
  ('Resistance Band Chest Press', 'Wyciskanie z gumą oporową', 'chest'::public.muscle_group),
  ('Single-Arm Dumbbell Press', 'Jednorącz wyciskanie hantla', 'chest'::public.muscle_group),
  ('Smith Machine Bench Press', 'Wyciskanie sztangi na maszynie Smitha', 'chest'::public.muscle_group),
  ('Smith Machine Incline Press', 'Wyciskanie na skosie w maszynie Smitha', 'chest'::public.muscle_group),
  ('Standing Cable Press', 'Wyciskanie na wyciągu stojąc', 'chest'::public.muscle_group),
  ('Suspension Trainer Chest Press', 'Wyciskanie na taśmach podwieszanych', 'chest'::public.muscle_group),
  ('Weighted Chest Dips', 'Pompki na poręczach z obciążeniem', 'chest'::public.muscle_group),
  ('Wide-Grip Push-Up', 'Pompki z szerokim rozstawem rąk', 'chest'::public.muscle_group),
  ('Assisted Pull-Up', 'Podciąganie z asystą', 'back'::public.muscle_group),
  ('Back Extension', 'Prostowanie grzbietu', 'back'::public.muscle_group),
  ('Barbell Deadlift', 'Martwy ciąg ze sztangą', 'back'::public.muscle_group),
  ('Barbell Pullover', 'Przenoszenie sztangi za głowę', 'back'::public.muscle_group),
  ('Barbell Row', 'Wiosłowanie sztangą', 'back'::public.muscle_group),
  ('Barbell Shrug', 'Wzruszenia ramion ze sztangą', 'back'::public.muscle_group),
  ('Cable Shrug', 'Wzruszenia ramion na wyciągu', 'back'::public.muscle_group),
  ('Chest-Supported Dumbbell Row', 'Wiosłowanie hantlami z podparciem klatki', 'back'::public.muscle_group),
  ('Chin-Up', 'Podciąganie podchwytem', 'back'::public.muscle_group),
  ('Close-Grip Cable Row', 'Wiosłowanie na wyciągu wąskim chwytem', 'back'::public.muscle_group),
  ('Close-Grip Lat Pulldown', 'Ściąganie drążka wąskim chwytem', 'back'::public.muscle_group),
  ('Dumbbell Pullover', 'Przenoszenie hantla za głowę', 'back'::public.muscle_group),
  ('Dumbbell Row', 'Wiosłowanie hantlem', 'back'::public.muscle_group),
  ('Dumbbell Shrug', 'Wzruszenia ramion z hantlami', 'back'::public.muscle_group),
  ('Face Pull', 'Przyciąganie liny do twarzy', 'back'::public.muscle_group),
  ('Good Morning', 'Dzień dobry ze sztangą', 'back'::public.muscle_group),
  ('Inverted Row', 'Wiosłowanie australijskie', 'back'::public.muscle_group),
  ('Lat Pulldown', 'Ściąganie drążka wyciągu górnego', 'back'::public.muscle_group),
  ('Machine High Row', 'Wiosłowanie na maszynie z góry', 'back'::public.muscle_group),
  ('Machine Pullover', 'Przenoszenie na maszynie', 'back'::public.muscle_group),
  ('Machine Row', 'Wiosłowanie na maszynie', 'back'::public.muscle_group),
  ('Neutral-Grip Lat Pulldown', 'Ściąganie drążka chwytem neutralnym', 'back'::public.muscle_group),
  ('Neutral-Grip Pull-Up', 'Podciąganie chwytem neutralnym', 'back'::public.muscle_group),
  ('Pendlay Row', 'Wiosłowanie Pendlay''a', 'back'::public.muscle_group),
  ('Pull-Up', 'Podciąganie na drążku', 'back'::public.muscle_group),
  ('Rack Pull', 'Martwy ciąg z podwyższenia', 'back'::public.muscle_group),
  ('Romanian Deadlift', 'Martwy ciąg rumuński', 'back'::public.muscle_group),
  ('Seated Cable Row', 'Wiosłowanie siedząc na wyciągu', 'back'::public.muscle_group),
  ('Single-Arm Dumbbell Row', 'Wiosłowanie hantlem jednorącz', 'back'::public.muscle_group),
  ('Straight-Arm Pulldown', 'Ściąganie prostych ramion na wyciągu', 'back'::public.muscle_group),
  ('T-Bar Row', 'Wiosłowanie na T-barze', 'back'::public.muscle_group),
  ('TRX Row', 'Wiosłowanie na taśmach TRX', 'back'::public.muscle_group),
  ('Weighted Pull-Up', 'Podciąganie z obciążeniem', 'back'::public.muscle_group),
  ('Wide-Grip Cable Row', 'Wiosłowanie na wyciągu szerokim chwytem', 'back'::public.muscle_group),
  ('Wide-Grip Lat Pulldown', 'Ściąganie drążka szerokim chwytem', 'back'::public.muscle_group),
  ('Arnold Press', 'Arnoldki', 'shoulders'::public.muscle_group),
  ('Band Pull-Apart', 'Rozciąganie gumy przed klatką', 'shoulders'::public.muscle_group),
  ('Barbell Front Raise', 'Unoszenie sztangi przodem', 'shoulders'::public.muscle_group),
  ('Barbell High Pull', 'Podciąganie sztangi do brody', 'shoulders'::public.muscle_group),
  ('Barbell Overhead Press', 'Wyciskanie sztangi nad głowę', 'shoulders'::public.muscle_group),
  ('Bent-Over Dumbbell Reverse Fly', 'Odwrotne rozpiętki z hantlami w opadzie', 'shoulders'::public.muscle_group),
  ('Cable Face Pull', 'Przyciąganie liny do twarzy na wyciągu', 'shoulders'::public.muscle_group),
  ('Cable Front Raise', 'Unoszenie ramienia przodem na wyciągu', 'shoulders'::public.muscle_group),
  ('Cable Lateral Raise', 'Unoszenie ramienia bokiem na wyciągu', 'shoulders'::public.muscle_group),
  ('Cable Rear Delt Fly', 'Unoszenie na tylny akton na wyciągu', 'shoulders'::public.muscle_group),
  ('Cable Upright Row', 'Wiosłowanie na wyciągu wzdłuż tułowia', 'shoulders'::public.muscle_group),
  ('Cable Y-Raise', 'Unoszenie na wyciągu w kształt litery Y', 'shoulders'::public.muscle_group),
  ('Dumbbell High Pull', 'Podciąganie hantli do brody', 'shoulders'::public.muscle_group),
  ('Dumbbell Lateral Raise', 'Unoszenie hantli bokiem', 'shoulders'::public.muscle_group),
  ('Dumbbell Shoulder Press', 'Wyciskanie hantli nad głowę', 'shoulders'::public.muscle_group),
  ('Dumbbell Y-Raise', 'Unoszenie hantli w kształt litery Y', 'shoulders'::public.muscle_group),
  ('Front Dumbbell Raise', 'Unoszenie hantli przodem', 'shoulders'::public.muscle_group),
  ('Handstand Push-Up', 'Pompki w staniu na rękach', 'shoulders'::public.muscle_group),
  ('Landmine Press', 'Wyciskanie półsztangi', 'shoulders'::public.muscle_group),
  ('Leaning Lateral Raise', 'Unoszenie hantla bokiem w pochyleniu', 'shoulders'::public.muscle_group),
  ('Machine Lateral Raise', 'Unoszenie bokiem na maszynie', 'shoulders'::public.muscle_group),
  ('Machine Shoulder Press', 'Wyciskanie na maszynie na barki', 'shoulders'::public.muscle_group),
  ('Pike Push-Up', 'Pompki pike', 'shoulders'::public.muscle_group),
  ('Plate Front Raise', 'Unoszenie talerza przodem', 'shoulders'::public.muscle_group),
  ('Push Jerk', 'Push Jerk', 'shoulders'::public.muscle_group),
  ('Push Press', 'Push Press', 'shoulders'::public.muscle_group),
  ('Reverse Cable Fly', 'Odwrotne rozpiętki na wyciągu', 'shoulders'::public.muscle_group),
  ('Reverse Dumbbell Fly', 'Odwrotne rozpiętki z hantlami', 'shoulders'::public.muscle_group),
  ('Reverse Pec Deck', 'Odwrotne rozpiętki na maszynie', 'shoulders'::public.muscle_group),
  ('Seated Barbell Shoulder Press', 'Wyciskanie sztangi siedząc', 'shoulders'::public.muscle_group),
  ('Seated Dumbbell Press', 'Wyciskanie hantli siedząc', 'shoulders'::public.muscle_group),
  ('Single-Arm Cable Lateral Raise', 'Jednorącz unoszenie bokiem na wyciągu', 'shoulders'::public.muscle_group),
  ('Single-Arm Dumbbell Press', 'Jednorącz wyciskanie hantla nad głowę', 'shoulders'::public.muscle_group),
  ('Smith Machine Shoulder Press', 'Wyciskanie na barki w maszynie Smitha', 'shoulders'::public.muscle_group),
  ('Upright Row', 'Wiosłowanie sztangą wzdłuż tułowia', 'shoulders'::public.muscle_group),
  ('Barbell Back Squat', 'Przysiad ze sztangą na plecach', 'legs'::public.muscle_group),
  ('Barbell Hip Thrust', 'Wypychanie bioder ze sztangą (Hip Thrust)', 'legs'::public.muscle_group),
  ('Barbell Step-Up', 'Wejścia na podwyższenie ze sztangą', 'legs'::public.muscle_group),
  ('Bulgarian Split Squat', 'Przysiad bułgarski', 'legs'::public.muscle_group),
  ('Cable Kickback', 'Odwodzenie nogi w tył na wyciągu', 'legs'::public.muscle_group),
  ('Cable Pull-Through', 'Przeciąganie liny między nogami', 'legs'::public.muscle_group),
  ('Curtsy Lunge', 'Wykrok ukłonowy', 'legs'::public.muscle_group),
  ('Dumbbell Split Squat', 'Przysiad wykroczny z hantlami', 'legs'::public.muscle_group),
  ('Forward Lunges', 'Wykroki w przód', 'legs'::public.muscle_group),
  ('Front Squat', 'Przysiad przedni', 'legs'::public.muscle_group),
  ('Glute Bridge', 'Mostek biodrowy', 'legs'::public.muscle_group),
  ('Goblet Squat', 'Przysiad goblet', 'legs'::public.muscle_group),
  ('Good Morning', 'Dzień dobry ze sztangą', 'legs'::public.muscle_group),
  ('Hack Squat', 'Przysiad na maszynie hack', 'legs'::public.muscle_group),
  ('Hip Abduction Machine', 'Odwodzenie nóg na maszynie', 'legs'::public.muscle_group),
  ('Hip Adduction Machine', 'Przywodzenie nóg na maszynie', 'legs'::public.muscle_group),
  ('Hip Thrust', 'Wypychanie bioder', 'legs'::public.muscle_group),
  ('Lateral Lunges', 'Wykroki boczne', 'legs'::public.muscle_group),
  ('Leg Extension', 'Prostowanie nóg na maszynie', 'legs'::public.muscle_group),
  ('Leg Press', 'Wypychanie ciężaru na suwnicy', 'legs'::public.muscle_group),
  ('Leg Press Calf Raise', 'Wspięcia na palce na suwnicy', 'legs'::public.muscle_group),
  ('Lying Leg Curl', 'Uginanie nóg leżąc', 'legs'::public.muscle_group),
  ('Nordic Hamstring Curl', 'Uginanie nordyckie', 'legs'::public.muscle_group),
  ('Reverse Lunges', 'Wykroki w tył', 'legs'::public.muscle_group),
  ('Romanian Deadlift', 'Martwy ciąg rumuński', 'legs'::public.muscle_group),
  ('Seated Calf Raise', 'Wspięcia na palce siedząc', 'legs'::public.muscle_group),
  ('Seated Leg Curl', 'Uginanie nóg siedząc', 'legs'::public.muscle_group),
  ('Single-Leg Glute Bridge', 'Mostek biodrowy na jednej nodze', 'legs'::public.muscle_group),
  ('Single-Leg Romanian Deadlift', 'Martwy ciąg rumuński na jednej nodze', 'legs'::public.muscle_group),
  ('Standing Calf Raise', 'Wspięcia na palce stojąc', 'legs'::public.muscle_group),
  ('Standing Leg Curl', 'Uginanie nogi stojąc na maszynie', 'legs'::public.muscle_group),
  ('Step-Up', 'Wejścia na podwyższenie', 'legs'::public.muscle_group),
  ('Stiff-Leg Deadlift', 'Martwy ciąg na prostych nogach', 'legs'::public.muscle_group),
  ('Tibialis Raise', 'Unoszenie palców stóp', 'legs'::public.muscle_group),
  ('Walking Lunges', 'Wykroki chodzone', 'legs'::public.muscle_group),
  ('21s Biceps Curl', 'Uginanie ramion 21', 'biceps'::public.muscle_group),
  ('Alternating Dumbbell Curl', 'Naprzemienne uginanie ramion z hantlami', 'biceps'::public.muscle_group),
  ('Alternating Hammer Curl', 'Naprzemienne uginanie młotkowe', 'biceps'::public.muscle_group),
  ('Band Hammer Curl', 'Uginanie młotkowe z gumą', 'biceps'::public.muscle_group),
  ('Barbell Curl', 'Uginanie ramion ze sztangą', 'biceps'::public.muscle_group),
  ('Bayesian Cable Curl', 'Uginanie bayesowskie na wyciągu', 'biceps'::public.muscle_group),
  ('Behind-the-Back Cable Curl', 'Uginanie na wyciągu zza pleców', 'biceps'::public.muscle_group),
  ('Cable Bayesian Curl', 'Uginanie bayesowskie jednorącz', 'biceps'::public.muscle_group),
  ('Cable Curl', 'Uginanie ramion na wyciągu', 'biceps'::public.muscle_group),
  ('Cable Preacher Curl', 'Uginanie na modlitewniku z wyciągiem', 'biceps'::public.muscle_group),
  ('Close-Grip Barbell Curl', 'Uginanie sztangi wąskim chwytem', 'biceps'::public.muscle_group),
  ('Concentration Curl', 'Uginanie koncentracyjne', 'biceps'::public.muscle_group),
  ('Cross-Body Hammer Curl', 'Uginanie młotkowe w poprzek tułowia', 'biceps'::public.muscle_group),
  ('Drag Curl', 'Uginanie typu drag curl', 'biceps'::public.muscle_group),
  ('Dumbbell Curl', 'Uginanie ramion z hantlami', 'biceps'::public.muscle_group),
  ('Dumbbell Preacher Curl', 'Uginanie hantla na modlitewniku', 'biceps'::public.muscle_group),
  ('EZ-Bar Curl', 'Uginanie ramion ze sztangą EZ', 'biceps'::public.muscle_group),
  ('Hammer Curl', 'Uginanie młotkowe', 'biceps'::public.muscle_group),
  ('High Cable Curl', 'Uginanie ramion na wysokim wyciągu', 'biceps'::public.muscle_group),
  ('Incline Dumbbell Curl', 'Uginanie hantli na ławce skośnej', 'biceps'::public.muscle_group),
  ('Incline Hammer Curl', 'Uginanie młotkowe na ławce skośnej', 'biceps'::public.muscle_group),
  ('Machine Biceps Curl', 'Uginanie ramion na maszynie', 'biceps'::public.muscle_group),
  ('Preacher Curl', 'Uginanie ramion na modlitewniku', 'biceps'::public.muscle_group),
  ('Resistance Band Curl', 'Uginanie ramion z gumą', 'biceps'::public.muscle_group),
  ('Reverse Curl', 'Uginanie ramion nachwytem', 'biceps'::public.muscle_group),
  ('Rope Cable Curl', 'Uginanie ramion z liną na wyciągu', 'biceps'::public.muscle_group),
  ('Rope Hammer Curl', 'Uginanie młotkowe z liną', 'biceps'::public.muscle_group),
  ('Seated Dumbbell Curl', 'Uginanie hantli siedząc', 'biceps'::public.muscle_group),
  ('Single-Arm Cable Curl', 'Jednorącz uginanie na wyciągu', 'biceps'::public.muscle_group),
  ('Spider Curl', 'Uginanie ramion typu spider', 'biceps'::public.muscle_group),
  ('Standing Dumbbell Curl', 'Uginanie hantli stojąc', 'biceps'::public.muscle_group),
  ('Suspension Biceps Curl', 'Uginanie ramion na taśmach podwieszanych', 'biceps'::public.muscle_group),
  ('TRX Biceps Curl', 'Uginanie ramion na taśmach TRX', 'biceps'::public.muscle_group),
  ('Wide-Grip Barbell Curl', 'Uginanie sztangi szerokim chwytem', 'biceps'::public.muscle_group),
  ('Zottman Curl', 'Uginanie Zottmana', 'biceps'::public.muscle_group),
  ('Assisted Dip', 'Pompki na poręczach z asystą', 'triceps'::public.muscle_group),
  ('Band Overhead Triceps Extension', 'Prostowanie ramion nad głową z gumą', 'triceps'::public.muscle_group),
  ('Band Triceps Pushdown', 'Prostowanie ramion z gumą', 'triceps'::public.muscle_group),
  ('Bench Close-Grip Push-Up', 'Pompki wąskie z rękami na ławce', 'triceps'::public.muscle_group),
  ('Bench Dips', 'Pompki odwrotne na ławce', 'triceps'::public.muscle_group),
  ('Bodyweight Triceps Extension', 'Prostowanie ramion z masą ciała', 'triceps'::public.muscle_group),
  ('Cable Kickback', 'Prostowanie ramienia na wyciągu w tył', 'triceps'::public.muscle_group),
  ('Close-Grip Bench Press', 'Wyciskanie sztangi wąskim chwytem', 'triceps'::public.muscle_group),
  ('Close-Grip Push-Up', 'Pompki wąskim chwytem', 'triceps'::public.muscle_group),
  ('Cross-Body Cable Extension', 'Prostowanie ramienia w poprzek tułowia na wyciągu', 'triceps'::public.muscle_group),
  ('Diamond Push-Up', 'Pompki diamentowe', 'triceps'::public.muscle_group),
  ('Dips', 'Pompki na poręczach', 'triceps'::public.muscle_group),
  ('Dumbbell Kickback', 'Prostowanie ramienia z hantlem w opadzie', 'triceps'::public.muscle_group),
  ('Dumbbell Overhead Extension', 'Prostowanie ramienia z hantlem nad głową', 'triceps'::public.muscle_group),
  ('Dumbbell Skull Crushers', 'Francuskie wyciskanie hantli', 'triceps'::public.muscle_group),
  ('EZ-Bar Skull Crushers', 'Francuskie wyciskanie sztangi EZ', 'triceps'::public.muscle_group),
  ('JM Press', 'Wyciskanie JM', 'triceps'::public.muscle_group),
  ('Machine Triceps Extension', 'Prostowanie ramion na maszynie', 'triceps'::public.muscle_group),
  ('Overhead Cable Extension', 'Prostowanie ramion nad głową na wyciągu', 'triceps'::public.muscle_group),
  ('Reverse-Grip Pushdown', 'Prostowanie ramion podchwytem', 'triceps'::public.muscle_group),
  ('Reverse-Grip Single-Arm Pushdown', 'Jednorącz prostowanie podchwytem', 'triceps'::public.muscle_group),
  ('Rope Overhead Extension', 'Prostowanie ramion nad głową z liną', 'triceps'::public.muscle_group),
  ('Rope Triceps Pushdown', 'Prostowanie ramion z liną', 'triceps'::public.muscle_group),
  ('Single-Arm Cable Overhead Extension', 'Jednorącz prostowanie nad głową na wyciągu', 'triceps'::public.muscle_group),
  ('Single-Arm Overhead Extension', 'Jednorącz prostowanie hantla nad głową', 'triceps'::public.muscle_group),
  ('Single-Arm Pushdown', 'Jednorącz prostowanie ramienia na wyciągu', 'triceps'::public.muscle_group),
  ('Skull Crushers', 'Francuskie wyciskanie leżąc', 'triceps'::public.muscle_group),
  ('Straight-Bar Pushdown', 'Prostowanie ramion z prostym drążkiem', 'triceps'::public.muscle_group),
  ('TRX Triceps Extension', 'Prostowanie ramion na taśmach TRX', 'triceps'::public.muscle_group),
  ('Tate Press', 'Wyciskanie Tate', 'triceps'::public.muscle_group),
  ('Triceps Kickback', 'Prostowanie ramienia w opadzie', 'triceps'::public.muscle_group),
  ('Triceps Pushdown', 'Prostowanie ramion na wyciągu', 'triceps'::public.muscle_group),
  ('V-Bar Pushdown', 'Prostowanie ramion z drążkiem V', 'triceps'::public.muscle_group),
  ('Weighted Dips', 'Pompki na poręczach z obciążeniem', 'triceps'::public.muscle_group),
  ('Ab Wheel Rollout', 'Rollout z kółkiem', 'core'::public.muscle_group),
  ('Back Extension', 'Prostowanie grzbietu', 'core'::public.muscle_group),
  ('Bicycle Crunch', 'Spięcia rowerowe', 'core'::public.muscle_group),
  ('Bird Dog', 'Bird dog', 'core'::public.muscle_group),
  ('Cable Crunch', 'Spięcia brzucha na wyciągu', 'core'::public.muscle_group),
  ('Cable Lift', 'Unoszenie diagonalne na wyciągu', 'core'::public.muscle_group),
  ('Cable Wood Chop', 'Rotacja tułowia na wyciągu', 'core'::public.muscle_group),
  ('Captain''s Chair Knee Raise', 'Unoszenie kolan na krześle rzymskim', 'core'::public.muscle_group),
  ('Crunch', 'Spięcia brzucha', 'core'::public.muscle_group),
  ('Dead Bug', 'Dead bug', 'core'::public.muscle_group),
  ('Decline Sit-Up', 'Brzuszki na ławce skośnej', 'core'::public.muscle_group),
  ('Farmer''s Walk', 'Spacer farmera', 'core'::public.muscle_group),
  ('Forearm Plank', 'Deska na przedramionach', 'core'::public.muscle_group),
  ('Glute Bridge March', 'Mostek biodrowy z naprzemiennym unoszeniem nóg', 'core'::public.muscle_group),
  ('Hanging Knee Raise', 'Unoszenie kolan w zwisie', 'core'::public.muscle_group),
  ('Hanging Leg Raise', 'Unoszenie nóg w zwisie', 'core'::public.muscle_group),
  ('High Plank', 'Deska na wyprostowanych ramionach', 'core'::public.muscle_group),
  ('Hollow Body Hold', 'Pozycja hollow body', 'core'::public.muscle_group),
  ('Hollow Body Rock', 'Kołyska w pozycji hollow body', 'core'::public.muscle_group),
  ('Kneeling Ab Wheel Rollout', 'Rollout z kółkiem z klęku', 'core'::public.muscle_group),
  ('Leg Raise', 'Unoszenie nóg', 'core'::public.muscle_group),
  ('Mountain Climbers', 'Bieg w podporze', 'core'::public.muscle_group),
  ('Pallof Press', 'Wyciskanie Pallofa', 'core'::public.muscle_group),
  ('Plank', 'Deska', 'core'::public.muscle_group),
  ('Plank Jack', 'Deska z odwodzeniem nóg', 'core'::public.muscle_group),
  ('Plank Shoulder Tap', 'Deska z dotykaniem barków', 'core'::public.muscle_group),
  ('Reverse Crunch', 'Spięcia odwrotne', 'core'::public.muscle_group),
  ('Russian Twist', 'Skręty rosyjskie', 'core'::public.muscle_group),
  ('Side Plank', 'Deska bokiem', 'core'::public.muscle_group),
  ('Sit-Up', 'Brzuszki', 'core'::public.muscle_group),
  ('Suitcase Carry', 'Spacer z ciężarem po jednej stronie', 'core'::public.muscle_group),
  ('Toe Touches', 'Dotykanie stóp', 'core'::public.muscle_group),
  ('Turkish Get-Up', 'Wstawanie tureckie', 'core'::public.muscle_group),
  ('V-Up', 'V-up', 'core'::public.muscle_group),
  ('Weighted Russian Twist', 'Skręty rosyjskie z obciążeniem', 'core'::public.muscle_group),
  ('Assault Bike', 'Jazda na rowerze Assault Bike', 'cardio'::public.muscle_group),
  ('Battle Rope Waves', 'Naprzemienne fale linami', 'cardio'::public.muscle_group),
  ('Battle Ropes', 'Liny treningowe', 'cardio'::public.muscle_group),
  ('Bear Crawl', 'Chód niedźwiedzia', 'cardio'::public.muscle_group),
  ('Box Jump', 'Wskoki na skrzynię', 'cardio'::public.muscle_group),
  ('Brisk Walking', 'Szybki marsz', 'cardio'::public.muscle_group),
  ('Broad Jump', 'Skok w dal z miejsca', 'cardio'::public.muscle_group),
  ('Burpees', 'Burpees', 'cardio'::public.muscle_group),
  ('Cycling', 'Jazda na rowerze', 'cardio'::public.muscle_group),
  ('Elliptical', 'Orbitrek', 'cardio'::public.muscle_group),
  ('High Knees', 'Bieg z wysokim unoszeniem kolan', 'cardio'::public.muscle_group),
  ('Hill Sprint', 'Sprint pod górę', 'cardio'::public.muscle_group),
  ('Incline Treadmill Walking', 'Marsz na bieżni pod górę', 'cardio'::public.muscle_group),
  ('Jump Rope', 'Skakanie na skakance', 'cardio'::public.muscle_group),
  ('Jump Squat', 'Przysiad z wyskokiem', 'cardio'::public.muscle_group),
  ('Jumping Jacks', 'Pajacyki', 'cardio'::public.muscle_group),
  ('Jumping Lunges', 'Wykroki z wyskokiem', 'cardio'::public.muscle_group),
  ('Kettlebell Swing', 'Wymach kettlebell', 'cardio'::public.muscle_group),
  ('Lateral Hops', 'Skoki boczne', 'cardio'::public.muscle_group),
  ('Mountain Climbers', 'Bieg w podporze', 'cardio'::public.muscle_group),
  ('Rowing Machine', 'Wiosłowanie na ergometrze', 'cardio'::public.muscle_group),
  ('Running', 'Bieg', 'cardio'::public.muscle_group),
  ('Shadow Boxing', 'Boksowanie z cieniem', 'cardio'::public.muscle_group),
  ('Skater Jumps', 'Skoki łyżwiarskie', 'cardio'::public.muscle_group),
  ('Ski Erg', 'Ergometr narciarski', 'cardio'::public.muscle_group),
  ('Sled Drag', 'Ciągnięcie sanek', 'cardio'::public.muscle_group),
  ('Sled Push', 'Pchanie sanek', 'cardio'::public.muscle_group),
  ('Spin Bike', 'Jazda na rowerze spinningowym', 'cardio'::public.muscle_group),
  ('Sprint', 'Sprint', 'cardio'::public.muscle_group),
  ('Stair Climber', 'Schody treningowe', 'cardio'::public.muscle_group),
  ('Stair Running', 'Bieg po schodach', 'cardio'::public.muscle_group),
  ('Stationary Bike', 'Jazda na rowerze stacjonarnym', 'cardio'::public.muscle_group),
  ('Step-Ups Cardio', 'Naprzemienne wejścia na podwyższenie', 'cardio'::public.muscle_group),
  ('Swimming', 'Pływanie', 'cardio'::public.muscle_group),
  ('Treadmill Running', 'Bieg na bieżni', 'cardio'::public.muscle_group),
  ('Barbell Clean and Press', 'Zarzut i wyciskanie sztangi', 'full_body'::public.muscle_group),
  ('Barbell Complex', 'Kompleks ćwiczeń ze sztangą', 'full_body'::public.muscle_group),
  ('Barbell Deadlift', 'Martwy ciąg ze sztangą', 'full_body'::public.muscle_group),
  ('Barbell Squat', 'Przysiad ze sztangą', 'full_body'::public.muscle_group),
  ('Bear Crawl', 'Chód niedźwiedzia', 'full_body'::public.muscle_group),
  ('Bear Crawl to Push-Up', 'Chód niedźwiedzia z pompką', 'full_body'::public.muscle_group),
  ('Burpee', 'Burpee', 'full_body'::public.muscle_group),
  ('Burpee Box Jump', 'Burpee ze wskokiem na skrzynię', 'full_body'::public.muscle_group),
  ('Clean and Jerk', 'Zarzut i podrzut', 'full_body'::public.muscle_group),
  ('Devil''s Press', 'Devil''s press', 'full_body'::public.muscle_group),
  ('Dumbbell Clean and Press', 'Zarzut i wyciskanie hantli', 'full_body'::public.muscle_group),
  ('Dumbbell Complex', 'Kompleks ćwiczeń z hantlami', 'full_body'::public.muscle_group),
  ('Dumbbell Man Maker', 'Man maker z hantlami', 'full_body'::public.muscle_group),
  ('Dumbbell Snatch', 'Rwanie hantla', 'full_body'::public.muscle_group),
  ('Dumbbell Squat to Press', 'Przysiad z wyciskaniem hantli', 'full_body'::public.muscle_group),
  ('Dumbbell Thruster', 'Thruster z hantlami', 'full_body'::public.muscle_group),
  ('Farmer''s Walk', 'Spacer farmera', 'full_body'::public.muscle_group),
  ('Front Squat', 'Przysiad przedni', 'full_body'::public.muscle_group),
  ('Hang Clean', 'Zarzut z pozycji zwisu', 'full_body'::public.muscle_group),
  ('Kettlebell Clean and Press', 'Zarzut i wyciskanie kettlebell', 'full_body'::public.muscle_group),
  ('Kettlebell Snatch', 'Rwanie kettlebell', 'full_body'::public.muscle_group),
  ('Kettlebell Swing', 'Wymach kettlebell', 'full_body'::public.muscle_group),
  ('Lunge to Biceps Curl', 'Wykrok z uginaniem ramion', 'full_body'::public.muscle_group),
  ('Man Maker', 'Man maker z hantlami', 'full_body'::public.muscle_group),
  ('Power Clean', 'Zarzut siłowy', 'full_body'::public.muscle_group),
  ('Renegade Row', 'Wiosłowanie renegata', 'full_body'::public.muscle_group),
  ('Renegade Row to Push-Up', 'Wiosłowanie renegata z pompką', 'full_body'::public.muscle_group),
  ('Sandbag Carry', 'Spacer z workiem treningowym', 'full_body'::public.muscle_group),
  ('Sandbag Clean', 'Zarzut worka treningowego', 'full_body'::public.muscle_group),
  ('Sled Push', 'Pchanie sanek', 'full_body'::public.muscle_group),
  ('Snatch', 'Rwanie', 'full_body'::public.muscle_group),
  ('Squat to Overhead Press', 'Przysiad z wyciskaniem nad głowę', 'full_body'::public.muscle_group),
  ('Thruster', 'Thruster ze sztangą lub hantlami', 'full_body'::public.muscle_group),
  ('Turkish Get-Up', 'Wstawanie tureckie', 'full_body'::public.muscle_group),
  ('Walking Lunge with Press', 'Wykroki z wyciskaniem', 'full_body'::public.muscle_group);
